name: Build Info

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch'
        required: false
      target_tenant:
        description: 'Target tenant'
        required: false
      target_environment:
        description: 'Target environment'
        required: false
      increment_patch_number:
        description: 'Increment patch number'
        required: false
        default: false

permissions:
  contents: write

env:
  BASE_VERSION: "8.9.0"
  TECHNICAL_VERSION: "8.9"
  MAJOR_VERSION: "8"
  MINOR_VERSION: "9"
  MARKETING_VERSION: "2022.1"
  PRE_RELEASE_TAG: "-maint"
  RELEASE_STREAM: "release/8.9"
  TARGET_BRANCH: ${{ github.event.inputs.target_branch || 'release/8.9' }}
  TARGET_TENANT: ${{ github.event.inputs.target_tenant || 'CiniWorld - 99Monthly' }}
  TARGET_ENVIRONMENT: ${{ github.event.inputs.target_environment || 'QA' }}

jobs:
  build-info:
    runs-on: ubuntu-latest
    outputs:
      build-name: ${{ steps.build-info.outputs.build-name }}
      registry-path: ${{ steps.build-info.outputs.registry-path }}
      registry-path-msi: ${{ steps.build-info.outputs.registry-path-msi }}
      major-version: ${{ steps.build-info.outputs.major-version }}
      minor-version: ${{ steps.build-info.outputs.minor-version }}
      patch-number: ${{ steps.build-info.outputs.patch-number }}
      build-number: ${{ steps.build-info.outputs.build-number }}
      product-release-stream: ${{ steps.build-info.outputs.product-release-stream }}
      target-branch: ${{ steps.build-info.outputs.target-branch }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Get Current Patch Number
        run: |
          GITHUB_TAG_PATTERN="${TECHNICAL_VERSION}.[0-9]*${PRE_RELEASE_TAG}+%y%j[0-9]*"
          GITHUB_TAG=$(git describe --tags --abbrev=0 --match="${GITHUB_TAG_PATTERN}" 2>/dev/null | awk 'NR==1{print $
